/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_form;

import Project_form.Siswa.FormSiswa;
import Project_form.Tagihan.FormDaftarTagihan;
import Project_form.Tingkatan.FormTingkatan;
import Project_form.Transaksi.FormTransaksi;

/**
 *
 * @author Eidoyonatan
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Splitpanemenu = new javax.swing.JSplitPane();
        LeftButton = new javax.swing.JPanel();
        btn_datasiswa = new javax.swing.JButton();
        btn_daftarTingkatan = new javax.swing.JButton();
        btn_daftarTagihan = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        rightpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        LeftButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_datasiswa.setText("Data Siswa");
        btn_datasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datasiswaActionPerformed(evt);
            }
        });

        btn_daftarTingkatan.setText("Daftar Tingkatan");
        btn_daftarTingkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarTingkatanActionPerformed(evt);
            }
        });

        btn_daftarTagihan.setText("Daftar Tagihan");
        btn_daftarTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarTagihanActionPerformed(evt);
            }
        });

        btn_transaksi.setText("Transaksi");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftButtonLayout = new javax.swing.GroupLayout(LeftButton);
        LeftButton.setLayout(LeftButtonLayout);
        LeftButtonLayout.setHorizontalGroup(
            LeftButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_datasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_daftarTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftButtonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_daftarTingkatan)))
                .addContainerGap())
        );
        LeftButtonLayout.setVerticalGroup(
            LeftButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftButtonLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(btn_datasiswa)
                .addGap(18, 18, 18)
                .addComponent(btn_daftarTingkatan)
                .addGap(18, 18, 18)
                .addComponent(btn_daftarTagihan)
                .addGap(18, 18, 18)
                .addComponent(btn_transaksi)
                .addGap(20, 20, 20))
        );

        Splitpanemenu.setLeftComponent(LeftButton);

        rightpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout rightpanelLayout = new javax.swing.GroupLayout(rightpanel);
        rightpanel.setLayout(rightpanelLayout);
        rightpanelLayout.setHorizontalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        rightpanelLayout.setVerticalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        Splitpanemenu.setRightComponent(rightpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Splitpanemenu, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Splitpanemenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_datasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datasiswaActionPerformed
        // TODO add your handling code here:
           rightpanel.removeAll();
        FormSiswa formSiswa = new FormSiswa();
        formSiswa.setFormUtama(this);
        rightpanel.add(formSiswa);
       formSiswa.setVisible(true);
        
        Splitpanemenu.setRightComponent(formSiswa);
        
    }//GEN-LAST:event_btn_datasiswaActionPerformed

    private void btn_daftarTingkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarTingkatanActionPerformed
        // TODO add your handling code here:
       rightpanel.removeAll();
        FormTingkatan formTingkatan = new FormTingkatan();
        formTingkatan.setFormUtama(this);
        rightpanel.add(formTingkatan);
        formTingkatan.setVisible(true);
        
        Splitpanemenu.setRightComponent(formTingkatan);
        
    }//GEN-LAST:event_btn_daftarTingkatanActionPerformed

    private void btn_daftarTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarTagihanActionPerformed
        // TODO add your handling code here:
        rightpanel.removeAll();
        FormDaftarTagihan formDaftarTagihan = new FormDaftarTagihan();
        formDaftarTagihan.setFormUtama(this);
        rightpanel.add(formDaftarTagihan);
        formDaftarTagihan.setVisible(true);
        
        Splitpanemenu.setRightComponent(formDaftarTagihan);
    }//GEN-LAST:event_btn_daftarTagihanActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
        rightpanel.removeAll();
        FormTransaksi formTransaksi = new FormTransaksi();
        formTransaksi.setFormUtama(this);
        rightpanel.add(formTransaksi);
        formTransaksi.setVisible(true);
        
        Splitpanemenu.setRightComponent(formTransaksi);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftButton;
    private javax.swing.JSplitPane Splitpanemenu;
    private javax.swing.JButton btn_daftarTagihan;
    private javax.swing.JButton btn_daftarTingkatan;
    private javax.swing.JButton btn_datasiswa;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel rightpanel;
    // End of variables declaration//GEN-END:variables
}
