/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_form.Transaksi;

import Project_Dao.DaoDaftarTagian;
import Project_Dao.DaoSiswa;
import Project_Dao.DaoTingkatan;
import Project_Dao.DaoTransaksi;
import Project_Entity.Siswa;
import Project_Entity.Tingkatan;
import Project_Entity.Transaksi;
import Project_form.FormUtama;
import Project_form.Siswa.FormEditSiswa;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eidoyonatan
 */
public class FormTransaksi extends javax.swing.JPanel {
    private DaoTransaksi daoTransaksi;
    private FormUtama formUtama;
    private DaoSiswa daoSiswa;
    private DaoTingkatan daoTingkatan;
    private DaoDaftarTagian daoDaftarTagian;

    public void setFormUtama(FormUtama formUtama) {
        this.formUtama = formUtama;
    }
          
    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        daoTransaksi = new DaoTransaksi();
        daoSiswa = new DaoSiswa();
        daoTingkatan = new DaoTingkatan();
        daoDaftarTagian = new DaoDaftarTagian();
        initComponents();   
        Refresh();
        
    }
    List<Transaksi> transaksis;

    public void Refresh() {
        transaksis = daoTransaksi.finds();
        Object[][] data = new Object[transaksis.size()][5];
        String header[] = {"Kode", "nama Siswa", "Tanggal", "Daftar Tagian", "harga"};

        int row = 0;
        for (Transaksi record : transaksis) {
            data[row][0] = record.getKode();
            data[row][1] = record.getSiswa().getNama();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String strTransdate = sdf.format(record.getTanggal());
            data[row][2] = strTransdate;
            data[row][3] = record.getDaftarTagian().getTagihan();
            data[row][4] = record.getHarga();
     

            row++;

        }
        DefaultTableModel model = new DefaultTableModel(data, header);
        tbtransaksi.setModel(model);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtransaksi = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        tbtransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtransaksi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        FormAddTransaksi add = new FormAddTransaksi();
        add.setDaoTransaksi(daoTransaksi);
        add.setVisible(true);

        Refresh();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
//         FormEditTransaksi formEditTransaksi = new FormEditTransaksi(formUtama, true);
//        formEditTransaksi.setDaoTransaksi(daoTransaksi);
//        int row = tbtransaksi.getSelectedRow();
//        String kode= tbtransaksi.getValueAt(row, 0).toString();
//        Transaksi temp2 = daoTransaksi.find(kode);
//        formEditTransaksi.setUpdateTransaksi(temp2);
//        formEditTransaksi.setVisible(true);
//        Refresh();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int select = JOptionPane.showConfirmDialog(formUtama, "apakah anda yakin", "confirmasi", JOptionPane.YES_NO_OPTION);
        if (select == JOptionPane.YES_OPTION) {
            int row = tbtransaksi.getSelectedRow();
         //  String kode = tbtransaksi.getValueAt(row, 0).toString();
         //  Transaksi tmp = daoTransaksi.find(kode);

          //  daoTingkatan.delete(tmp);
            Refresh();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtransaksi;
    // End of variables declaration//GEN-END:variables
}
