/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_form.Tingkatan;

import Project_Dao.DaoTingkatan;
import Project_Entity.DaftarTagian;
import Project_Entity.Tingkatan;
import Project_form.FormUtama;
import Project_form.Tagihan.FormEditDaftarTagihan;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eidoyonatan
 */
public class FormTingkatan extends javax.swing.JPanel {
    
    private FormUtama formUtama;
    private DaoTingkatan daoTingkatan;
    

    public void setFormUtama(FormUtama formUtama) {
        this.formUtama = formUtama;
    }

    /**
     * Creates new form FormTingkatan
     */
    public FormTingkatan() {
        initComponents();
        daoTingkatan = new DaoTingkatan();
        Refresh();
    }
    public void Refresh(){
        List<Tingkatan> tingkatans = daoTingkatan.finds();
        String[][] data = new String[tingkatans.size()][2];
        String header[] = {"Kode", "Tingkatan"};
        
        int row = 0;
        for (Tingkatan record : tingkatans){
            data[row][0]= record.getKode();
            data[row][1]= record.getTingkatan();
            row++;
            
        }
        DefaultTableModel model = new DefaultTableModel(data, header);
        tbtingkatan.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtingkatan = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        tbtingkatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtingkatan);

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btn_add)
                        .addGap(15, 15, 15)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
      
       // FormAddTingkatan add = new FormAddTingkatan(formUtama, true);
        FormAddTingkatan add = new FormAddTingkatan();
        add.setDaoTingkatan(daoTingkatan);
        add.setFormTingkatan(this);
        add.setVisible(true);
        
        Refresh();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        FormEditTingkatan formEditTingkatan = new FormEditTingkatan(formUtama, true);
        formEditTingkatan.setDaoTingkatan(daoTingkatan);
        int row = tbtingkatan.getSelectedRow();
        String kode = tbtingkatan.getValueAt(row, 0).toString();
        Tingkatan temp = daoTingkatan.find(kode);
        formEditTingkatan.setUpdateTingkatan(temp);
        formEditTingkatan.setVisible(true);
        Refresh();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
         int select = JOptionPane.showConfirmDialog(formUtama, "apakah anda yakin", "confirmasi", JOptionPane.YES_NO_OPTION);
        if (select == JOptionPane.YES_OPTION) {
            int row = tbtingkatan.getSelectedRow();
            String selectedCode = tbtingkatan.getValueAt(row, 0).toString();
            Tingkatan tmp = daoTingkatan.find(selectedCode);

            daoTingkatan.delete(tmp);
            Refresh();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtingkatan;
    // End of variables declaration//GEN-END:variables
}
