/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_form.Tagihan;

import Project_Dao.DaoDaftarTagian;
import Project_Entity.DaftarTagian;
import Project_Entity.Siswa;
import Project_Entity.Tingkatan;
import Project_form.FormUtama;
import Project_form.Siswa.FormEditSiswa;
import Project_form.Tingkatan.FormAddTingkatan;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eidoyonatan
 */
public class FormDaftarTagihan extends javax.swing.JPanel {
    
    private FormUtama formUtama;

    public void setFormUtama(FormUtama formUtama) {
        this.formUtama = formUtama;
    }
    
    
    DaoDaftarTagian daoDaftarTagian;
    /**
     * Creates new form FormDaftarTagihan
     */
    public FormDaftarTagihan() {
        initComponents();
        daoDaftarTagian = new DaoDaftarTagian();        
        Refresh();
    }
    
     public void Refresh(){
        List<DaftarTagian> daftarTagians = daoDaftarTagian.finds();
        String[][] data = new String[daftarTagians.size()][2];
        String header[] = {"Kode", "Daftar Tagihan"};
        
        int row = 0;
        for (DaftarTagian record : daftarTagians){
            data[row][0]= record.getKode();
            data[row][1]= record.getTagihan();
            row++;
            
        }
        DefaultTableModel model = new DefaultTableModel(data, header);
        tbdaftartagian.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdaftartagian = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        tbdaftartagian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbdaftartagian);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete)
                .addGap(224, 224, 224))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        FormAddDaftarTagihan addDaftarTagihan= new FormAddDaftarTagihan();
        addDaftarTagihan.setDaoDaftarTagian(daoDaftarTagian);
        addDaftarTagihan.setFormDaftarTagihan(this);
        addDaftarTagihan.setVisible(true);
        
        Refresh();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int select = JOptionPane.showConfirmDialog(formUtama, "apakah anda yakin", "confirmasi", JOptionPane.YES_NO_OPTION);
        if (select == JOptionPane.YES_OPTION) {
            int row = tbdaftartagian.getSelectedRow();
            String selectedCode = tbdaftartagian.getValueAt(row, 0).toString();
            DaftarTagian tmp = daoDaftarTagian.find(selectedCode);

            daoDaftarTagian.delete(tmp);
            Refresh();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        FormEditDaftarTagihan formEditDaftarTagihan = new FormEditDaftarTagihan(formUtama, true);
        formEditDaftarTagihan.setDaoDaftarTagian(daoDaftarTagian);
        int row = tbdaftartagian.getSelectedRow();
        String kode = tbdaftartagian.getValueAt(row, 0).toString();
        DaftarTagian temp = daoDaftarTagian.find(kode);
        formEditDaftarTagihan.setUpdatedaDaftarTagian(temp);
        formEditDaftarTagihan.setVisible(true);
        Refresh();
    }//GEN-LAST:event_btn_editActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdaftartagian;
    // End of variables declaration//GEN-END:variables
}
